version: '3.8'

services:

  db:
    image: postgres:15.2
    container_name: best_travel
    restart: always

    environment:
      POSTGRES_DB: best_travel
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: password987
      TZ: America/Argentina/Buenos_Aires
      PGTZ: America/Argentina/Buenos_Aires

    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql

    ports:
      - "5432:5432"